[package]
name = "shiny-bot"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
anyhow = "1.0.68"
poise = "0.6.1"
shuttle-runtime = "0.45.0"
shuttle-serenity = "0.45.0"
tracing = "0.1.37"
tokio = "1.26.0"
rand = "0.8.5"
ring = "0.17.8"
chrono = "0.4.38"
